// <auto-generated />
using System;
using CFPService;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CFPService.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240331213714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CFPService.Activities", b =>
                {
                    b.Property<string>("Activity")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Activity");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Activity = "Report",
                            Description = "Доклад, 35-45 минут"
                        },
                        new
                        {
                            Activity = "Masterclass",
                            Description = "Мастеркласс, 1-2 часа"
                        },
                        new
                        {
                            Activity = "Discussion",
                            Description = "Дискуссия / круглый стол, 40-50 минут"
                        });
                });

            modelBuilder.Entity("CFPService.Applications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityName")
                        .HasColumnType("text");

                    b.Property<Guid>("Author")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasMaxLength(1000)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Outline")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityName");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CFPService.Applications", b =>
                {
                    b.HasOne("CFPService.Activities", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityName");

                    b.Navigation("Activity");
                });
#pragma warning restore 612, 618
        }
    }
}
